[package]
name = "pandoc-notion"
version = "0.1.0"
edition = "2024"

[dependencies]
pandoc_types = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
notion-client = "1.0.8"

[dev-dependencies]
pretty_assertions = "1.3.0"
# Dependencies used only for tests
